


export const FETCH_SERVICES_SUCCESS = 'FETCH_SERVICES_SUCCESS'
export const FETCH_SERVICE_SUCCESS = 'FETCH_SERVICE_SUCCESS'
export const REQUEST_SERVICE = 'REQUEST_SERVICE'
export const SET_AUTH_USER = 'SET_AUTH_USER'
export const RESET_AUTH_STATE = 'RESET_AUTH_STATE'